# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Licitacoes.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(681, 499)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 671, 371))
        self.scrollArea.setStyleSheet("#scrollArea {\n"
"background-color: rgb(85, 255, 127);\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 648, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.CardLicitacao = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.CardLicitacao.setGeometry(QtCore.QRect(1, 1, 647, 101))
        self.CardLicitacao.setStyleSheet("#CardLicitacao {\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background:  rgb(237, 247, 245);\n"
"}")
        self.CardLicitacao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CardLicitacao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CardLicitacao.setObjectName("CardLicitacao")
        self.label = QtWidgets.QLabel(self.CardLicitacao)
        self.label.setGeometry(QtCore.QRect(12, 5, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_2.setGeometry(QtCore.QRect(268, 27, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_3.setGeometry(QtCore.QRect(346, 27, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_4.setGeometry(QtCore.QRect(414, 27, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_5.setGeometry(QtCore.QRect(11, 28, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_6.setGeometry(QtCore.QRect(160, 1, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_7.setObjectName("label_7")
        self.lcdNumber = QtWidgets.QLCDNumber(self.CardLicitacao)
        self.lcdNumber.setGeometry(QtCore.QRect(270, 50, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.CardLicitacao)
        self.lcdNumber_2.setGeometry(QtCore.QRect(340, 50, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.CardLicitacao)
        self.lcdNumber_3.setGeometry(QtCore.QRect(410, 50, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label_8 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_8.setGeometry(QtCore.QRect(321, 2, 101, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_9.setGeometry(QtCore.QRect(70, 5, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_10.setGeometry(QtCore.QRect(60, 30, 211, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.CardLicitacao)
        self.label_11.setGeometry(QtCore.QRect(120, 50, 71, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.CardLicitacao)
        self.pushButton.setGeometry(QtCore.QRect(518, 2, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.CardLicitacao)
        self.pushButton_2.setGeometry(QtCore.QRect(518, 33, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.CardLicitacao)
        self.pushButton_3.setGeometry(QtCore.QRect(518, 64, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.CardLicitacao)
        self.progressBar.setGeometry(QtCore.QRect(272, 79, 241, 16))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.CardLicitacao_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.CardLicitacao_2.setGeometry(QtCore.QRect(0, 110, 647, 101))
        self.CardLicitacao_2.setStyleSheet("#CardLicitacao_2 {\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background:  rgb(237, 247, 245);\n"
"}")
        self.CardLicitacao_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CardLicitacao_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CardLicitacao_2.setObjectName("CardLicitacao_2")
        self.label_26 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_26.setGeometry(QtCore.QRect(12, 5, 61, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_27.setGeometry(QtCore.QRect(268, 27, 71, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_28.setGeometry(QtCore.QRect(346, 27, 55, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_29.setGeometry(QtCore.QRect(414, 27, 55, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_30.setGeometry(QtCore.QRect(11, 28, 55, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_31.setGeometry(QtCore.QRect(160, 1, 111, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_32.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_32.setObjectName("label_32")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.CardLicitacao_2)
        self.lcdNumber_7.setGeometry(QtCore.QRect(270, 50, 64, 23))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.CardLicitacao_2)
        self.lcdNumber_8.setGeometry(QtCore.QRect(340, 50, 64, 23))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.CardLicitacao_2)
        self.lcdNumber_9.setGeometry(QtCore.QRect(410, 50, 64, 23))
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.label_33 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_33.setGeometry(QtCore.QRect(321, 2, 101, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_34.setGeometry(QtCore.QRect(70, 5, 55, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_35.setGeometry(QtCore.QRect(60, 30, 211, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.CardLicitacao_2)
        self.label_36.setGeometry(QtCore.QRect(120, 50, 71, 16))
        self.label_36.setObjectName("label_36")
        self.pushButton_7 = QtWidgets.QPushButton(self.CardLicitacao_2)
        self.pushButton_7.setGeometry(QtCore.QRect(518, 2, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.CardLicitacao_2)
        self.pushButton_8.setGeometry(QtCore.QRect(518, 33, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.CardLicitacao_2)
        self.pushButton_9.setGeometry(QtCore.QRect(518, 64, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.progressBar_3 = QtWidgets.QProgressBar(self.CardLicitacao_2)
        self.progressBar_3.setGeometry(QtCore.QRect(272, 79, 241, 16))
        self.progressBar_3.setProperty("value", 70)
        self.progressBar_3.setObjectName("progressBar_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(2, 23, 301, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.dateEdit = QtWidgets.QDateEdit(self.tab)
        self.dateEdit.setGeometry(QtCore.QRect(310, 23, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab)
        self.dateEdit_2.setGeometry(QtCore.QRect(430, 23, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(550, 10, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(550, 30, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(313, 4, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(432, 4, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(3, 4, 55, 16))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Licitaçoes"))
        self.label.setText(_translate("Dialog", "Licitaçao:  "))
        self.label_2.setText(_translate("Dialog", "Contratado"))
        self.label_3.setText(_translate("Dialog", "Enviado"))
        self.label_4.setText(_translate("Dialog", "Restante"))
        self.label_5.setText(_translate("Dialog", "Cliente:"))
        self.label_6.setText(_translate("Dialog", "Data de expiração"))
        self.label_7.setText(_translate("Dialog", "Data de cadastro:"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "250537"))
        self.label_10.setText(_translate("Dialog", "INSS"))
        self.label_11.setText(_translate("Dialog", "15/10/2018"))
        self.pushButton.setText(_translate("Dialog", "Entregar"))
        self.pushButton_2.setText(_translate("Dialog", "Editar"))
        self.pushButton_3.setText(_translate("Dialog", "Relatorio"))
        self.progressBar.setFormat(_translate("Dialog", "%p%"))
        self.label_26.setText(_translate("Dialog", "Licitaçao:  "))
        self.label_27.setText(_translate("Dialog", "Contratado"))
        self.label_28.setText(_translate("Dialog", "Enviado"))
        self.label_29.setText(_translate("Dialog", "Restante"))
        self.label_30.setText(_translate("Dialog", "Cliente:"))
        self.label_31.setText(_translate("Dialog", "Data de expiração"))
        self.label_32.setText(_translate("Dialog", "Data de cadastro:"))
        self.label_33.setText(_translate("Dialog", "TextLabel"))
        self.label_34.setText(_translate("Dialog", "25099"))
        self.label_35.setText(_translate("Dialog", "Ministerio da Educaçao"))
        self.label_36.setText(_translate("Dialog", "03/10/2018"))
        self.pushButton_7.setText(_translate("Dialog", "Entregar"))
        self.pushButton_8.setText(_translate("Dialog", "Editar"))
        self.pushButton_9.setText(_translate("Dialog", "Relatorio"))
        self.progressBar_3.setFormat(_translate("Dialog", "%p%"))
        self.radioButton.setText(_translate("Dialog", "Expiraçao"))
        self.radioButton_2.setText(_translate("Dialog", "Cadastro"))
        self.label_12.setText(_translate("Dialog", "Data Inicial"))
        self.label_13.setText(_translate("Dialog", "Data Final"))
        self.label_14.setText(_translate("Dialog", "Cliente"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Licitaçoes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Cadastro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

